pip3 install Flask
pip3 install flask_login
pip3 install flask-wtf
pip3 install flask-sqlalchemy
pip3 install flask-migrate
pip3 install email-validator
pip3 install flask-babel
pip3 install colorlog
pip3 install picamera